services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DMK\Mkvarnish\:
        resource: '../Classes/*'

    DMK\Mkvarnish\Utility\Headers:
        public: true
